In [36]:
# 1.Create an array of 10 zeros
from numpy import*
a = array((0,0,0,0,0,0,0,0,0,0)) # one dimensional array
print(a)
print(np.__version__)

[0 0 0 0 0 0 0 0 0 0]
1.20.3


In [11]:
# 2.Create an array of 10 ones
a = np.array([1,1,1,1,1,1,1,1,1,1]) # one dimensional array
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [12]:
# 3.Create an array of 10 fives
a = np.array([5,5,5,5,5,5,5,5,5,5]) # one dimensional array
print(a)

[5 5 5 5 5 5 5 5 5 5]


In [31]:
#4.Create an array of the integers from 10 to 50
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [32]:
# 5.Create an array of all the even integers from 10 to 50
arr = np.arange(0,51,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [57]:
# 6.Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [59]:
#7.Create a 3x3 identity matrix
import numpy as np
arr = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [98]:
# 8.Use NumPy to generate a random number between 0 and 1
from numpy import random
x = random.rand()
print(x)

0.4675417462407938


In [104]:
# 9.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
rand_num = np.random.normal(0,1,25)
print(rand_num)


[ 0.47138048  0.16518388  0.01169535 -1.22741234  1.21789285 -2.05500696
 -1.07860648  0.41668808 -2.33931564  0.0280904  -0.01684968  0.41129736
 -1.55465465  0.8218987  -1.5251645  -0.02948747  1.03930804 -2.10998469
  2.35492574  1.77311653  0.57825685  1.20082037 -0.6953672  -1.01119891
 -0.38210694]


In [118]:
# 10.Create the following matrix
arr = np.arange(0,1+0.01,0.01)
print(arr)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [119]:
# 11.Create an array of 20 linearly spaced points between 0 and 1
num_line = np.linspace(0,1,20)
print(num_line)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [120]:
# 12.Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs
n = np.arange(1,26).reshape(5,5)
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [153]:
# 13.
l = np.arange(12,26)
l1 = l.tolist()
l2 = []
print(type(l))
print(type(l1))
for i in l1:
    if i != 16 and i != 21:
        l2.append(i)
print(l2)
a = np.array(l2)
print(a.reshape(3,4))

<class 'numpy.ndarray'>
<class 'list'>
[12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [154]:
# 14.
x = np.array([[[2],[7],[12]]])
print(x)

[[[ 2]
  [ 7]
  [12]]]


In [155]:
#15.
x1 = np.arange(21,26)
print(x1)

[21 22 23 24 25]


In [157]:
# 16.
s = np.arange(16,26).reshape(2,5)
print(s)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [11]:
# 17.Get the sum of all the values in matrix in python
import numpy as np
s = np.arange(1,26)
s1 = s.tolist()
sum1 = 0
sum = 0
c = 0
x1 = []
x2 = 0
for i in range(len(s1)):
    c = c+1
    sum = sum+s1[i]
x = sum//c
print(sum)
print(x)
for i in s1:
    sum1 = (i-x)**2
    x1.append(sum1)
for i in x1:
    x2 = x2+i
l = x2//(c-1)
print(l**0.5)   

325
13
7.3484692283495345


In [31]:
# 18.sum of all the columns in the matrix
import numpy as np
x = np.arange(1,26).reshape(5,5)
x2 = []
n = 0
for i in range(5):
    sum = 0
    x1 = x[:,i]
    for i in x1:
        sum = sum+i
    x2.append(sum)
print(x2)
x3 = np.array(x2)
print(x3)
print(type(x3))

[55, 60, 65, 70, 75]
[55 60 65 70 75]
<class 'numpy.ndarray'>
